apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuntamiento-api-deployment
  namespace: trabajo-final
  labels:
    app: ayuntamiento-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayuntamiento-api
  template:
    metadata:
      labels:
        app: ayuntamiento-api
    spec:
      containers:
        - name: spring-app
          image: zyeraix/ayuntamiento-api:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1