apiVersion: apps/v1
kind: Deployment
metadata:
  name: seguridad-api-deployment
  namespace: trabajo-final
  labels:
    app: seguridad-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seguridad-api
  template:
    metadata:
      labels:
        app: seguridad-api
    spec:
      containers:
        - name: spring-app
          image: zyeraix/security-api:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1