apiVersion: v1
kind: Pod
metadata:
  name: estaciones-mongo
  namespace: trabajo-final
  labels:
    app: estaciones-mongo
spec:
  containers:
    - name: estaciones-mongodb
      image: mongo:4.4
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mongo-persistent-storage
      persistentVolumeClaim:
        claimName: estaciones-mongo-volume-claim
    - name: init-script
      configMap:
        name: estaciones-mongo-init-script
  restartPolicy: Never
