apiVersion: v1
kind: Service
metadata:
  name: aparcamientos-repomysql-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: aparcamientos-repomysql
  ports:
    - port: 80
      targetPort: 80
