apiVersion: v1
kind: Service
metadata:
  name: ayuntamiento-repomongo-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: ayuntamiento-repomongo
  ports:
    - port: 80
      targetPort: 80
