apiVersion: v1
kind: Service
metadata:
  name: ayuntamiento-api-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: ayuntamiento-api
  ports:
    - port: 80
      targetPort: 80
