apiVersion: v1
kind: Service
metadata:
  name: estaciones-repomysql-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: estaciones-repomysql
  ports:
    - port: 80
      targetPort: 80
