version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: twcam23$
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
