apiVersion: v1
kind: Service
metadata:
  name: aparcamientos-mysql-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: aparcamientos-mysql
  ports:
    - port: 3306
      targetPort: 3306
