apiVersion: v1
kind: Service
metadata:
  name: estaciones-mongo-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: estaciones-mongo
  ports:
    - port: 27017
      targetPort: 27017
