apiVersion: v1
kind: Service
metadata:
  name: estaciones-mysql-service
  namespace: trabajo-final
spec:
  type: ClusterIP
  selector:
    app: estaciones-mysql
  ports:
    - port: 3306
      targetPort: 3306
