apiVersion: v1
kind: ConfigMap
metadata:
  name: aparcamientos-mysql-init-script
  namespace: trabajo-final
data:
  init.sql: |
    -- Parking database
    CREATE DATABASE IF NOT EXISTS parkingdb;
    USE parkingdb;
    
    CREATE TABLE IF NOT EXISTS parking (
        id VARCHAR(255) PRIMARY KEY,
        direction VARCHAR(255),
        bikes_capacity INT,
        latitude FLOAT,
        longitude FLOAT
    );
    
    -- Inserta datos en la tabla parking solo si no existen
    INSERT INTO parking (id, direction, bikes_capacity, latitude, longitude) 
    SELECT 'P1', 'Avenida de la Paz', 100, 40.4168, -3.7038 WHERE NOT EXISTS (SELECT 1 FROM parking WHERE id = 'P1');
    INSERT INTO parking (id, direction, bikes_capacity, latitude, longitude) 
    SELECT 'P2', 'Calle Gran Vía', 80, 40.4204, -3.7050 WHERE NOT EXISTS (SELECT 1 FROM parking WHERE id = 'P2');
    INSERT INTO parking (id, direction, bikes_capacity, latitude, longitude) 
    SELECT 'P3', 'Plaza Mayor', 120, 40.4155, -3.7075 WHERE NOT EXISTS (SELECT 1 FROM parking WHERE id = 'P3');
    INSERT INTO parking (id, direction, bikes_capacity, latitude, longitude) 
    SELECT 'P4', 'Calle Serrano', 90, 40.4276, -3.6880 WHERE NOT EXISTS (SELECT 1 FROM parking WHERE id = 'P4');
    INSERT INTO parking (id, direction, bikes_capacity, latitude, longitude) 
    SELECT 'P5', 'Paseo del Prado', 150, 40.4131, -3.6918 WHERE NOT EXISTS (SELECT 1 FROM parking WHERE id = 'P5');
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
